'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ChevronLeft,ChevronRight,Expand,RefreshCw,X} from 'lucide-react';
import {EVENT_CHECKED,eventPhotos,eventProducts,type EventProduct} from '../lib/event-content';
import {API_BASE,today} from '../lib/daily';
import type {Product} from '../services/topten';

export default function Events(){
 const track=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDialogElement>(null),position=useRef(0);
 const [active,setActive]=useState(0),[photo,setPhoto]=useState<{src:string;title:string}|null>(null),[zoom,setZoom]=useState(false);
 const total=eventPhotos.length+1+eventProducts.length;
 function go(index:number){const el=track.current;if(!el)return;el.scrollTo({left:index*el.clientWidth,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
 useEffect(()=>{const el=track.current;if(!el)return;const observer=new ResizeObserver(()=>el.scrollTo({left:position.current*el.clientWidth,behavior:'instant'}));observer.observe(el);return()=>observer.disconnect();},[]);
 useEffect(()=>{if(photo){setZoom(false);dialog.current?.showModal();}else dialog.current?.close();},[photo]);
 return <section className="events">
  <div className="event-heading"><div><span className="event-kicker">OCTOBER 2026 · STAFF EDIT</span><h1>10월, 이야기할 상품들</h1><p>한두 문장으로 바로 전하는 고객 안내 멘트.</p></div><span className="event-month">10<span>EVENT</span></span></div>
  <div className="event-toolbar"><div className="event-sections" aria-label="이벤트 구간"><button aria-pressed={active<3} onClick={()=>go(0)}>사진 3장</button><button aria-pressed={active>=3&&active<6} onClick={()=>go(3)}>에어테크</button><button aria-pressed={active>=6} onClick={()=>go(6)}>먼슬리 5</button></div><span className="event-swipe">옆으로 넘겨 보세요 <ChevronRight size={15}/></span></div>
  <div className="event-track" ref={track} role="region" aria-roledescription="carousel" aria-label="10월 이벤트 슬라이드" tabIndex={0} onKeyDown={e=>{if(e.target!==e.currentTarget)return;if(e.key==='ArrowRight'){e.preventDefault();go(Math.min(total-1,active+1));}if(e.key==='ArrowLeft'){e.preventDefault();go(Math.max(0,active-1));}}} onScroll={()=>{const el=track.current;if(!el)return;const index=Math.max(0,Math.min(total-1,Math.round(el.scrollLeft/el.clientWidth)));position.current=index;setActive(index);}}>
   {eventPhotos.map((item,i)=><article className="event-slide event-poster" key={item.id} role="group" aria-roledescription="slide" aria-label={`${i+1} / ${total} ${item.title}`} inert={active!==i}><button className="event-poster-image" onClick={()=>setPhoto(item)} aria-label={`${item.title} 크게 보기`}><img src={item.src} alt={item.title} loading={i===0?'eager':'lazy'} decoding="async"/><span><Expand size={16}/>눌러서 크게 보기</span></button><div className="event-poster-caption"><span>GALLERY 0{i+1}</span><h2>{item.title}</h2><p>{item.caption}</p></div></article>)}
   <article className="event-slide event-overview" role="group" aria-roledescription="slide" aria-label={`4 / ${total} 에어테크 핵심 요약`} inert={active!==3}><div className="event-overview-hero"><span>AIRTECH</span><h2>가볍게 입고,<br/>온기를 지키다.</h2><p>섬유 사이의 공기층을 만드는<br/>탑텐의 충전재 기술</p><button onClick={()=>setPhoto(eventPhotos[0])}>원본 자료 보기 <Expand size={16}/></button></div><div className="event-overview-body"><span className="event-kicker">10월 셀링포인트 · 에어테크</span><h3>고객님께 한마디</h3><div className="event-pitch"><p>“공기층이 온기를 잡아줘 가볍고 따뜻하게 입기 좋아요.”</p></div><details className="event-details"><summary>특징 · 관리법 더 보기</summary><dl><div><dt>가벼움</dt><dd>오래 입어도 부담 적은 착용감</dd></div><div><dt>따뜻함</dt><dd>섬유 사이 공기층으로 온기 유지</dd></div><div><dt>쉬운 관리</dt><dd>케어 안내에 따른 기계세탁 가능</dd></div><div><dt>형태 유지</dt><dd>충전재의 볼륨과 실루엣 유지</dd></div></dl><div className="event-care"><b>세탁 안내도 함께</b><p>중성세제 · 30℃ 이하 약하게 세탁. 뒤집어 세탁망 사용, 널어서 자연건조. 드라이클리닝·건조기 사용 불가. 개별 제품 케어라벨도 확인하세요.</p></div><p className="event-source-note">자료의 가격 인하 사례는 89,900원 → 69,900원입니다. 제품별 가격은 다음 카드에서 확인하세요.</p></details><button className="event-next-pick" onClick={()=>go(4)}>전지현 픽 2종 보기 <ChevronRight size={17}/></button></div></article>
   {eventProducts.map((item,i)=><article className="event-slide" key={item.id} role="group" aria-roledescription="slide" aria-label={`${i+5} / ${total} ${item.title}`} inert={active!==i+4}><EventCard item={item} onPhoto={setPhoto}/></article>)}
  </div>
  <div className="event-navigation"><button aria-label="이전 슬라이드" disabled={active===0} onClick={()=>go(active-1)}><ChevronLeft size={22}/></button><div className="event-dots">{Array.from({length:total},(_,i)=><button key={i} aria-label={`${i+1}번 슬라이드`} aria-current={active===i?'true':undefined} onClick={()=>go(i)}><span/></button>)}</div><span className="event-counter" aria-live="polite">{String(active+1).padStart(2,'0')} / {total}</span><button aria-label="다음 슬라이드" disabled={active===total-1} onClick={()=>go(active+1)}><ChevronRight size={22}/></button></div>
  <p className="event-footnote">셀링포인트: 제공된 10월 자료를 정리한 직원용 안내 · 상품 사진·가격: TOPTEN 공식몰 · 판매 멘트는 응대 예시입니다.</p>
  <dialog className="event-lightbox" ref={dialog} onCancel={()=>setPhoto(null)} onClick={e=>{if(e.target===e.currentTarget)setPhoto(null);}}><div className="event-lightbox-bar"><b>{photo?.title}</b><button onClick={()=>setZoom(v=>!v)}>{zoom?'화면에 맞추기':'확대'}</button><button aria-label="사진 닫기" onClick={()=>setPhoto(null)}><X size={22}/></button></div><div className="event-lightbox-scroll">{photo&&<img className={zoom?'is-zoomed':''} src={photo.src} alt={photo.title} referrerPolicy="no-referrer"/>}</div></dialog>
 </section>;
}

function EventCard({item,onPhoto}:{item:EventProduct;onPhoto:(value:{src:string;title:string})=>void}){
 const [live,setLive]=useState<Product|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[checked,setChecked]=useState(EVENT_CHECKED),[broken,setBroken]=useState(false);
 const src=live?.image||item.image,price=live?.price??item.price,normalPrice=live?.normalPrice??item.normalPrice;
 async function refresh(){if(busy)return;setBusy(true);setError('');try{const res=await fetch(`${API_BASE}/api/products/${item.variant}?refresh=1`,{cache:'no-store',signal:AbortSignal.timeout(45_000)});if(!res.ok)throw Error();const data=await res.json() as Product;if(data.status!=='found'||data.price===undefined||data.price===null)throw Error();setLive(data);setChecked(today());setBroken(false);}catch{setError('최신 정보를 가져오지 못해 마지막 확인 가격을 표시합니다. 공식몰에서 확인해 주세요.');}finally{setBusy(false);}}
 return <div className="event-product"><button className="event-product-image" onClick={()=>onPhoto({src,title:item.name})} aria-label={`${item.name} 사진 크게 보기`}>{broken?<span>상품 사진을 불러오지 못했습니다.<br/>아래 공식몰에서 확인해 주세요.</span>:<img src={src} alt={item.name} loading="lazy" decoding="async" referrerPolicy="no-referrer" onError={()=>setBroken(true)}/>}<span className="event-product-tag">{item.group}</span><span className="event-image-expand"><Expand size={18}/></span></button><div className="event-product-body"><span className="event-kicker">{item.group}</span><h2>{item.title}</h2><p className="event-product-subtitle">{item.subtitle}</p><div className="event-product-meta"><span>{item.code}</span><b>{price.toLocaleString()}원</b>{normalPrice>price&&<del>{normalPrice.toLocaleString()}원</del>}</div><p className="event-price-date">공식몰 표시가 · {checked} 확인 · 행사·매장에 따라 달라질 수 있어요.</p><div className="event-pitch"><span>고객님께 한마디</span><p>“{item.pitch}”</p></div><details className="event-details"><summary>특징 · 관리법 더 보기</summary><ul className="event-points">{item.points.map(p=><li key={p}>{p}</li>)}</ul></details>{item.note&&<p className="event-match-note">{item.note}</p>}<div className="event-product-actions"><a href={live?.url||item.url} target="_blank" rel="noreferrer">공식몰 상품 보기 <ArrowUpRight size={16}/></a><button disabled={busy} onClick={refresh}><RefreshCw size={14} className={busy?'spin':''}/>{busy?'확인 중…':'가격 새로고침'}</button></div>{error&&<p className="event-match-note" role="status">{error}</p>}</div></div>;
}
