'use client';
import {useRef,useState,type RefObject,type FormEvent} from 'react';
import {Search,ChevronRight} from 'lucide-react';
import {API_BASE} from '../lib/daily';
import {suggestNames} from '../lib/location-suggestions.mjs';
type Item={name:string;aliases:string;group:string;floor:string};
export default function LocationSearch({query,onChange,onChoose,onSubmit,inputRef}:{query:string;onChange:(v:string)=>void;onChoose:(v:string)=>void;onSubmit:(e:FormEvent)=>void;inputRef:RefObject<HTMLInputElement|null>}){
 const [items,setItems]=useState<Item[]>([]),[open,setOpen]=useState(false),[active,setActive]=useState(-1),[loading,setLoading]=useState(false),[failed,setFailed]=useState(false);
 const last=useRef(0),pending=useRef(false);
 const matches:Item[]=suggestNames(items,query);const shown=open&&query.trim().length>0;
 async function load(){setOpen(true);if(pending.current||Date.now()-last.current<60000)return;pending.current=true;setLoading(true);setFailed(false);try{const r=await fetch(API_BASE+'/api/locations',{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error();const data=await r.json() as {items:Item[]};setItems(data.items);last.current=Date.now();}catch{setFailed(true);}finally{pending.current=false;setLoading(false);}}
 function choose(name:string){setOpen(false);setActive(-1);onChoose(name);}
 return <form className="search-form location-autocomplete" onSubmit={e=>{setOpen(false);onSubmit(e);}} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setOpen(false);}}><Search size={18}/><input ref={inputRef} value={query} onFocus={()=>void load()} onChange={e=>{onChange(e.target.value);setOpen(true);setActive(-1);}} placeholder="품번 또는 옷 이름 검색" aria-label="품번 또는 옷 이름 검색" maxLength={80} role="combobox" aria-autocomplete="list" aria-expanded={shown&&matches.length>0} aria-controls="location-name-suggestions" aria-activedescendant={shown&&active>=0&&matches[active]?`location-name-${active}`:undefined} autoComplete="off" onKeyDown={e=>{if(e.nativeEvent.isComposing||e.keyCode===229)return;if(e.key==='Escape'){setOpen(false);setActive(-1);}if(e.key==='ArrowDown'&&matches.length){e.preventDefault();setOpen(true);setActive(i=>(i+1)%matches.length);}if(e.key==='ArrowUp'&&matches.length){e.preventDefault();setOpen(true);setActive(i=>(i-1+matches.length)%matches.length);}if(e.key==='Enter'&&shown&&active>=0&&matches[active]){e.preventDefault();choose(matches[active].name);}}}/><button aria-label="검색" type="submit"><ChevronRight size={18}/></button>{shown&&<div className="name-suggestions"><div id="location-name-suggestions" role="listbox" aria-label="관련 옷 이름">{matches.map((item,i)=><button key={item.name} id={`location-name-${i}`} type="button" role="option" aria-selected={active===i} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(item.name)}><Search size={15}/><span>{item.name}<small>{item.group} · {item.floor}</small></span><ChevronRight size={15}/></button>)}</div>{!matches.length&&<p role="status">{loading?'관련 이름을 찾는 중…':failed?'추천을 불러오지 못했습니다. 검색 버튼으로 다시 찾아보세요.':'등록된 연관 이름이 없습니다. 검색 버튼으로 위치를 찾아보세요.'}</p>}</div>}</form>;
}
