'use client';
import {useEffect,useRef,useState} from 'react';
import {MapPin,X} from 'lucide-react';
import {API_BASE} from '../lib/daily';

type Item={id:string;name:string;aliases:string;floor:string;group:string;location:string};
type Catalog={items:Item[];revision:string;updatedAt?:string};
const blank=():Item=>({id:crypto.randomUUID(),name:'',aliases:'',floor:'',group:'공용',location:''});
const normalize=(s:string)=>s.toLowerCase().replace(/\s/g,'');
async function readCatalog(){const r=await fetch(API_BASE+'/api/locations',{cache:'no-store',signal:AbortSignal.timeout(45000)});if(!r.ok)throw Error('매장 위치를 불러오지 못했습니다.');return r.json() as Promise<Catalog>;}
export default function Locations({query,adminRequest}:{query:string;adminRequest:number}){
 const [catalog,setCatalog]=useState<Catalog>({items:[],revision:'0'}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[group,setGroup]=useState('전체'),[editing,setEditing]=useState(false),[retry,setRetry]=useState(0);
 const seen=useRef(adminRequest);
 useEffect(()=>{if(seen.current!==adminRequest){seen.current=adminRequest;setEditing(true);}},[adminRequest]);
 useEffect(()=>{let cancelled=false;setLoading(true);setError('');readCatalog().then(v=>{if(!cancelled)setCatalog(v);}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[retry]);
 const words=query.trim().toLowerCase().split(/\s+/).filter(Boolean);
 const items=catalog.items.filter(item=>(group==='전체'||item.group===group)&&words.every(w=>normalize([item.name,item.aliases,item.floor,item.group,item.location].join(' ')).includes(normalize(w))));
 return <section className="locations"><div className="location-heading"><div><h2><MapPin size={22}/>옷 이름으로 위치 찾기</h2><p>상단 검색창에 ‘그래픽 후드’처럼 입력하세요.</p></div><button className="manual-entry" onClick={()=>setEditing(true)}>위치 관리</button></div><div className="location-filters">{['전체','남성','여성','키즈','공용'].map(g=><button key={g} aria-pressed={group===g} onClick={()=>setGroup(g)}>{g}</button>)}</div>
 {loading?<p role="status">매장 위치를 불러오는 중…</p>:error?<p role="alert">{error}<button className="manual-entry" onClick={()=>setRetry(n=>n+1)}>다시 시도</button></p>:!catalog.items.length?<div className="schedule-empty"><MapPin size={32}/><h3>아직 등록된 위치가 없어요</h3><p>관리자가 옷 이름과 위치를 등록하면 여기서 찾을 수 있습니다.</p></div>:!items.length?<p className="schedule-empty">일치하는 위치가 없습니다. ‘후드’처럼 짧게 검색해 보세요.</p>:<div className="location-grid">{items.map(item=><article key={item.id}><span>{item.group} · {item.floor}</span><h3>{item.name}</h3><p><MapPin size={18}/>{item.location}</p>{item.aliases&&<small>다른 이름: {item.aliases}</small>}</article>)}</div>}
 {editing&&<Editor onClose={()=>setEditing(false)} onSave={v=>{setCatalog(v);setError('');setLoading(false);setEditing(false);}}/>}</section>;
}
function Editor({onClose,onSave}:{onClose:()=>void;onSave:(c:Catalog)=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const [token,setToken]=useState(''),[password,setPassword]=useState(''),[catalog,setCatalog]=useState<Catalog|null>(null),[item,setItem]=useState<Item>(blank),[busy,setBusy]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{dialog.current?.showModal();try{setToken(sessionStorage.getItem('topten.admin.session')||'');}catch{}},[]);
 useEffect(()=>{let stop=false;setCatalog(null);readCatalog().then(v=>{if(!stop){setCatalog(v);setError('');}}).catch(e=>{if(!stop)setError(e.message);});return()=>{stop=true;};},[retry]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch(API_BASE+'/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password}),signal:AbortSignal.timeout(45000)});const d=await r.json() as {token:string;error?:string};if(!r.ok)throw Error(d.error||'로그인 실패');setToken(d.token);setPassword('');sessionStorage.setItem('topten.admin.session',d.token);}catch(e){setError(e instanceof Error?e.message:'로그인 실패');}finally{setBusy(false);}}
 async function save(e:React.FormEvent){e.preventDefault();if(!catalog)return;setBusy(true);setError('');const exists=catalog.items.some(v=>v.id===item.id);try{const r=await fetch(API_BASE+'/api/locations',{method:'PUT',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({revision:catalog.revision,items:exists?catalog.items.map(v=>v.id===item.id?item:v):[...catalog.items,item]}),signal:AbortSignal.timeout(45000)});const d=await r.json() as Catalog&{error?:string};if(r.status===401){setToken('');sessionStorage.removeItem('topten.admin.session');}if(!r.ok)throw Error(d.error||'저장 실패');onSave(d);}catch(e){setError(e instanceof Error?e.message:'저장 실패');}finally{setBusy(false);}}
 return <dialog ref={dialog} className="daily-editor location-editor" onCancel={e=>{if(busy)e.preventDefault();else onClose();}}><div className="sheet-heading"><b>매장 위치 관리</b><button disabled={busy} aria-label="닫기" onClick={onClose}><X size={20}/></button></div>{!token?<form className="daily-form" onSubmit={login}><label>관리자 암호<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy}>관리자 열기</button></form>:!catalog?<><p>위치 정보를 불러오는 중입니다.</p><button className="manual-entry" onClick={()=>setRetry(n=>n+1)}>다시 불러오기</button></>:<form onSubmit={save}><fieldset disabled={busy} className="schedule-fields daily-form"><label>등록 또는 수정<select value={catalog.items.some(v=>v.id===item.id)?item.id:''} onChange={e=>setItem(catalog.items.find(v=>v.id===e.target.value)||blank())}><option value="">새 위치 등록</option>{catalog.items.map(v=><option key={v.id} value={v.id}>{v.name} · {v.floor}</option>)}</select></label><label>옷 이름<input required maxLength={80} placeholder="예: 남성 그래픽 후드" value={item.name} onChange={e=>setItem({...item,name:e.target.value})}/></label><label>다른 검색 이름<input maxLength={200} placeholder="예: 프린팅 후드, 그림 후드, 후드티" value={item.aliases} onChange={e=>setItem({...item,aliases:e.target.value})}/></label><label>구분<select value={item.group} onChange={e=>setItem({...item,group:e.target.value})}>{['공용','남성','여성','키즈'].map(g=><option key={g}>{g}</option>)}</select></label><label>층<input required maxLength={20} placeholder="예: 1층" value={item.floor} onChange={e=>setItem({...item,floor:e.target.value})}/></label><label>진열 위치<input required maxLength={200} placeholder="예: 남성 구역 입구 왼쪽 두 번째 행거" value={item.location} onChange={e=>setItem({...item,location:e.target.value})}/></label><small>같은 종류가 여러 곳에 있으면 위치별로 따로 등록하세요.</small><button className="primary" disabled={busy}>{busy?'저장 중…':'매장 위치 공유 저장'}</button></fieldset></form>}{error&&<p className="closing-warning" role="alert">{error}</p>}</dialog>;
}
