'use client';
import {memo,useEffect,useRef,useState} from 'react';
import {Star,ImageIcon,X} from 'lucide-react';
import type {Row} from '../lib/report';
import type {Product} from '../services/topten';
import {productStorage,safeLink,type Notes} from '../lib/product-storage';
import {validation} from '../services/ocr/validation.mjs';
import {briefing} from '../lib/briefing.mjs';
export default memo(function ProductCard({row,p,scope,date,favorite,onStar,onCopy,onRefresh}:{row:Row;p?:Product;other?:Row;scope:string;date:string;favorite:boolean;onStar:()=>void;onPhoto:()=>void;onCopy:(text:string)=>void;onRefresh:()=>void}){
 const [notes,setNotes]=useState<Notes>({location:'',display:''}),[bad,setBad]=useState(false),[open,setOpen]=useState(false),[notice,setNotice]=useState('');const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{setNotes(productStorage.read(row.code));},[row.code]);
 useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close();},[open]);
 function change(next:Notes){setNotes(next);try{productStorage.write(row.code,next);setNotice('');}catch{setNotice('메모를 저장하지 못했어요.');}}
 const verified=row.rank===0?p?.status==='found'&&!p.stale:validation(row,p).verified;
 // Exact-code lookup can be shown for comparison without claiming OCR is verified.
 const info:Partial<Product>={...(p?.status==='found'?p:{}),...notes.manual};
 useEffect(()=>setBad(false),[info.image]);
 const message=briefing(row,{...(p?.status==='found'?p:{}),...notes.manual},notes,date,scope);
 const photo=safeLink(info.image)&&!bad?<img src={safeLink(info.image)} alt={info.name||row.code} width={160} height={210} loading="lazy" decoding="async" referrerPolicy="no-referrer" onError={()=>setBad(true)}/>:<span className="placeholder"><ImageIcon size={24}/><span>눌러서 메모</span></span>;
 return <><article className="card store-card"><div className="card-image"><button className="photo" aria-label={row.code+' 사진·메모 열기'} onClick={()=>setOpen(true)}>{photo}</button>{row.rank>0&&<span className="rank">#{row.rank}</span>}<button className={'favorite '+(favorite?'selected':'')} aria-label={favorite?'즐겨찾기 해제':'즐겨찾기 추가'} aria-pressed={favorite} onClick={onStar}><Star size={18} fill={favorite?'currentColor':'none'}/></button></div><div className="card-body"><h3>{info.name||row.code}</h3><div className="price">{info.normalPrice!=null&&info.normalPrice!==info.price&&<small className="normal-price"><s>{info.normalPrice.toLocaleString()}원</s></small>}{info.price!=null?info.price.toLocaleString()+'원':'가격 확인 필요'}</div><button className="code" onClick={()=>onCopy(row.code)}>{row.code}</button>{row.rank>0&&<p className="sales-line">판매수량 {row.quantity!=null?row.quantity+' PCS':'-'}</p>}<label style={{display:'block',marginTop:14,fontSize:13,fontWeight:700,color:'#555'}}>매장 내 위치<input value={notes.location} placeholder="예: 1층 입구 / 여성 벽면" maxLength={100} onChange={e=>change({...notes,location:e.target.value})} style={{display:'block',width:'100%',maxWidth:260,height:38,boxSizing:'border-box',marginTop:6,padding:'0 10px',border:'1px solid #d9d9d9',borderRadius:7,fontSize:14,background:'#fff'}}/></label><button className="card-note-button" onClick={()=>setOpen(true)}>대본 보기</button></div></article>
 <dialog ref={dialog} className="product-sheet" onCancel={()=>setOpen(false)} onClick={e=>e.target===e.currentTarget&&setOpen(false)}><div className="sheet-heading"><div><b>{info.name||row.code}</b><small>{row.code}</small></div><button aria-label="상품 메모 닫기" onClick={()=>setOpen(false)}><X size={22}/></button></div>{safeLink(info.image)&&!bad&&<img className="sheet-photo" src={safeLink(info.image)} alt={info.name||row.code} referrerPolicy="no-referrer" onError={()=>setBad(true)}/>}<div className="product-notes"><label>진열/적재<input value={notes.display} placeholder="행거 진열" maxLength={100} onChange={e=>change({...notes,display:e.target.value})}/></label></div><small className="muted">이 기기에 자동 저장</small>{notice&&<p role="alert">{notice}</p>}<div className="brief-text"><p>{message}</p><button onClick={()=>onCopy(message)}>대본 복사</button></div><div className="small-actions"><a href={safeLink(info.url)||'https://display-topten10.goodwearmall.com/search?keyword='+row.code} target="_blank" rel="noreferrer">공식몰 보기</a><button onClick={onRefresh}>사진·가격 새로고침</button></div><details className="manual-details"><summary>상품정보 직접 수정</summary><form className="manual-product" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget),price=String(data.get('price')||''),image=String(data.get('image')||''),url=String(data.get('url')||'');if((image&&!safeLink(image))||(url&&!safeLink(url))){setNotice('https 주소를 입력해 주세요.');return;}change({...notes,manual:{name:String(data.get('name')||''),price:price===''?undefined:Number(price),image:safeLink(image),url:safeLink(url)}});setNotice('저장했어요.');}}><label>상품명<input name="name" defaultValue={info.name} maxLength={160}/></label><label>현재가 (원)<input name="price" type="number" min="0" max="99999999" defaultValue={info.price}/></label><label>이미지 주소<input name="image" type="url" defaultValue={info.image}/></label><label>상품 링크<input name="url" type="url" defaultValue={info.url}/></label><button type="submit">저장</button><button type="button" onClick={()=>change({...notes,manual:undefined})}>직접 입력 해제</button></form></details></dialog></>;
});
